# Generated by Django 4.2.2 on 2023-06-28 06:52

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Item Code')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Unit of measure code')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Vendor Code')),
                ('description', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phone_field.models.PhoneField(max_length=31)),
                ('address', models.CharField(max_length=200)),
                ('kra_pin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LPO',
            fields=[
                ('number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=200, verbose_name='Item Batch Number')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(verbose_name='Unit Price')),
                ('expiry_date', models.DateField(verbose_name='Expiry date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.items')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.units'),
        ),
    ]
