# Generated by Django 4.2.2 on 2023-06-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Item Code')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=200, verbose_name='Item Batch Number')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(verbose_name='Unit Price')),
                ('total', models.IntegerField()),
                ('expiry_date', models.DateField(verbose_name='Expiry date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Items', related_query_name='item_code', to='inventory.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='lpo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='lpo',
            name='vendor',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='LPO',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vendors', related_query_name='vendor_code', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', related_query_name='item_code', to='inventory.unit'),
        ),
    ]
