# Generated by Django 4.2.2 on 2023-06-28 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_item_purchaseorder_remove_lpo_item_remove_lpo_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Create', related_query_name='LPO_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modify', related_query_name='LPO_modify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=inventory.models.AlphanumericAutoField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Unit of measure code'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, verbose_name='Vendor Code'),
        ),
    ]
