# Generated by Django 4.2.2 on 2023-06-28 12:35

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchaseorder_created_at_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=inventory.models.AlphanumericAutoField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Unit of measure code'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Vendor Code'),
        ),
    ]
