# Generated by Django 4.2.2 on 2023-06-28 12:46

from django.db import migrations
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_code_alter_purchaseorder_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=inventory.models.VendorCode(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Vendor Code'),
        ),
    ]
