# Generated by Django 4.2.2 on 2023-06-28 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_alter_vendor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('number', inventory.models.AlphanumericAutoField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=0, editable=False)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Create', related_query_name='Create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Modify', related_query_name='Modify', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200, verbose_name='Item Batch Number')),
                ('quantity_requested', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField(verbose_name='Unit Price')),
                ('total', models.IntegerField(editable=False)),
                ('expiry_date', models.DateField(verbose_name='Expiry date')),
                ('quantity_received', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', related_query_name='Items', to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=inventory.models.VendorCode(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Vendor Code'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Items', related_query_name='Items', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Header', related_query_name='Header', to='inventory.purchaseheader'),
        ),
        migrations.AddField(
            model_name='purchaseheader',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Vendors', related_query_name='vendor_code', to='inventory.vendor'),
        ),
    ]
