# Generated by Django 4.2.2 on 2023-06-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchaseheader_purchaseline_alter_item_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lpo', related_query_name='lpo', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', related_query_name='lines', to='inventory.purchaseheader'),
        ),
    ]
