# Generated by Django 4.2.2 on 2023-06-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_purchaseline_item_alter_purchaseline_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor', related_query_name='vendor', to='inventory.vendor'),
        ),
    ]
