# Generated by Django 4.2.2 on 2023-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_purchaseheader_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
