# Generated by Django 4.2.2 on 2023-07-03 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_alter_purchaseline_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseheader',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lpo', related_query_name='lpo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseheader',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lpo_m', related_query_name='lpo_m', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SalesHeader',
            fields=[
                ('number', inventory.models.SalesInvoice(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('customer', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', related_query_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200, verbose_name='Batch Number')),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('cost', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('expiry_status', models.BooleanField(default=False)),
                ('document_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_entry', related_query_name='item_entry', to='inventory.purchaseline')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn', related_query_name='grn', to='inventory.item')),
            ],
        ),
    ]
