# Generated by Django 4.2.2 on 2023-07-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_saleslines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementry',
            name='document_no',
        ),
        migrations.AddField(
            model_name='itementry',
            name='purchase_doc_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_entry', related_query_name='item_entry', to='inventory.purchaseline', verbose_name='Purchase Document Number'),
        ),
        migrations.AddField(
            model_name='itementry',
            name='sales_doc_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_entry', related_query_name='items_entry', to='inventory.saleslines', verbose_name='Sales Document Number'),
        ),
    ]
