# Generated by Django 4.2.2 on 2023-07-05 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_itementry_document_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='source_code',
            field=models.CharField(default=datetime.datetime(2023, 7, 5, 13, 13, 40, 43118, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
