# Generated by Django 4.2.2 on 2023-07-05 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_itementry_source_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itementry',
            options={'verbose_name_plural': 'Item Entries'},
        ),
        migrations.AddField(
            model_name='itementry',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
