# Generated by Django 4.2.2 on 2023-07-06 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_itementry_options_itementry_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementry',
            name='sales_doc_no',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='invoice_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Vendor Invoice Number'),
        ),
        migrations.AddField(
            model_name='saleslines',
            name='batch',
            field=models.CharField(default=datetime.datetime(2023, 7, 6, 12, 50, 48, 545369, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
