# Generated by Django 4.2.2 on 2023-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_itementry_sales_doc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslines',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
