# Generated by Django 4.2.2 on 2023-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_saleslines_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='purchaseheader',
            options={'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='salesheader',
            options={'verbose_name_plural': 'Sales Invoices'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Units Of Measure'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterField(
            model_name='saleslines',
            name='total',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='saleslines',
            name='unit_price',
            field=models.IntegerField(editable=False),
        ),
    ]
