# Generated by Django 4.2.2 on 2023-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_item_options_alter_purchaseheader_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslines',
            name='batch',
        ),
    ]
