# Generated by Django 4.2.2 on 2023-07-08 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_saleslines_lpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslines',
            name='batch',
            field=models.CharField(default=datetime.datetime(2023, 7, 8, 9, 17, 58, 109333, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleslines',
            name='lpo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', related_query_name='sales', to='inventory.itementry'),
        ),
    ]
