# Generated by Django 4.2.2 on 2023-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_salesheader_finalize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesheader',
            name='finalize',
            field=models.BooleanField(default=True),
        ),
    ]
