# Generated by Django 4.2.2 on 2023-07-10 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0025_alter_salesheader_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseheader',
            name='status',
            field=models.CharField(choices=[(0, 'Open'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Cancelled Approval')], default=0, max_length=30),
        ),
        migrations.CreateModel(
            name='ApprovalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(0, 'Open'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Cancelled Approval')], max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(default=datetime.datetime(2023, 7, 10, 7, 39, 36, 757185, tzinfo=datetime.timezone.utc))),
                ('overdue', models.BooleanField(default=False)),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_amount', related_query_name='approval_amount', to='inventory.purchaseheader')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', related_query_name='approver', to=settings.AUTH_USER_MODEL)),
                ('document_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval', related_query_name='approval', to='inventory.purchaseheader')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier', related_query_name='modifier', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requestor', related_query_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
