# Generated by Django 4.2.2 on 2023-07-10 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_purchaseheader_status_approvalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalentry',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 7, 40, 17, 518195, tzinfo=datetime.timezone.utc)),
        ),
    ]
