# Generated by Django 4.2.2 on 2023-07-10 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_approvalentry_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalentry',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
