# Generated by Django 4.2.2 on 2023-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_purchaseline_markup_alter_itementry_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='batch',
            field=models.CharField(max_length=200, null=True, verbose_name='Item Batch Number'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='expiry_date',
            field=models.DateField(null=True, verbose_name='Expiry date'),
        ),
    ]
