# Generated by Django 4.2.2 on 2023-07-23 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_purchaseline_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslines',
            name='discount',
            field=models.PositiveSmallIntegerField(default=40, help_text='Allowed Precentage Discount', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
