# Generated by Django 4.2.2 on 2023-07-23 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_salescreditmemoheader_salescreditmemoline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescreditmemoline',
            name='sales_line',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='inventory.saleslines'),
            preserve_default=False,
        ),
    ]
