# Generated by Django 4.2.2 on 2023-07-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_salescreditmemoline_sales_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesCreditMemoLine',
        ),
    ]
