# Generated by Django 4.2.2 on 2023-07-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_salescreditmemoheader_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescreditmemoline',
            name='sales_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_line', related_query_name='sales_line', to='inventory.saleslines'),
        ),
    ]
