# Generated by Django 4.2.2 on 2023-07-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0039_salescreditmemoheader_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCreditMemoHeader',
            fields=[
                ('number', inventory.models.PurchaseCreditMemo(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_memo', related_query_name='purchase_memo', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memo', related_query_name='memo', to='inventory.purchaseheader')),
            ],
            options={
                'verbose_name_plural': 'Purchase Credit Memos',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='salescreditmemoline',
            name='item_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return', related_query_name='sales_return', to='inventory.itementry'),
        ),
        migrations.CreateModel(
            name='PurchaseCreditMemoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('unit_price', models.PositiveIntegerField(editable=False)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('item_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return', related_query_name='purchase_return', to='inventory.itementry')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line', related_query_name='line', to='inventory.purchasecreditmemoheader')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_line', related_query_name='purchase_line', to='inventory.purchaseline')),
            ],
        ),
    ]
