# Generated by Django 4.2.2 on 2023-07-28 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_item_created_by_vendor_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslines',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Allowed Precentage Discount', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
