# Generated by Django 4.2.2 on 2023-07-28 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_saleslines_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='quantity_requested',
            field=models.PositiveIntegerField(help_text='Quantity'),
        ),
    ]
