# Generated by Django 4.2.2 on 2023-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_itementry_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='unit_price',
            field=models.FloatField(verbose_name='Unit Price'),
        ),
    ]
