# Generated by Django 4.2.2 on 2023-08-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_alter_salescreditmemoline_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecreditmemoline',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', related_query_name='lines', to='inventory.purchasecreditmemoheader'),
        ),
    ]
