# Generated by Django 4.2.2 on 2023-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_purchasecreditmemoline_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslines',
            name='unit_price',
            field=models.FloatField(editable=False),
        ),
    ]
