# Generated by Django 4.2.2 on 2023-08-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_alter_saleslines_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['code'], 'verbose_name_plural': 'Units Of Measure'},
        ),
    ]
