# Generated by Django 4.2.3 on 2023-08-20 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0052_approvalsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalsetup',
            name='modified_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='modifier_id', related_query_name='modifier_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
