# Generated by Django 4.2.2 on 2023-09-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalentry',
            options={'ordering': ['id'], 'permissions': [('inventory_read_approvalentry', 'Read approval entries')], 'verbose_name_plural': 'Approval Entries'},
        ),
    ]
