# Generated by Django 4.2.2 on 2023-09-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_alter_approvalentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalentry',
            options={'ordering': ['id'], 'verbose_name_plural': 'Approval Entries'},
        ),
    ]
