# Generated by Django 4.2.2 on 2023-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_alter_approvalentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalentry',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
