# Generated by Django 4.2.2 on 2023-10-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0063_approvalentry_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itementry",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="itementry",
            name="sale",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
