# Generated by Django 4.2.2 on 2023-10-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0064_alter_itementry_cost_alter_itementry_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleslines",
            name="total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="saleslines",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
