# Generated by Django 4.2.2 on 2023-10-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0065_alter_saleslines_total_alter_saleslines_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itementry",
            name="cost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="itementry",
            name="sale",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="saleslines",
            name="total",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="saleslines",
            name="unit_price",
            field=models.FloatField(editable=False),
        ),
    ]
