# Generated by Django 4.2.2 on 2023-10-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0067_alter_itementry_cost_alter_itementry_sale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseheader",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
