# Generated by Django 4.2.2 on 2023-10-23 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0068_alter_purchaseheader_total_alter_purchaseline_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="markup",
            field=models.DecimalField(
                decimal_places=2,
                default=40,
                help_text="Percentage Markup",
                max_digits=6,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
