# Generated by Django 4.2.2 on 2023-10-27 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0070_alter_saleslines_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalsetup",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creator_id",
                related_query_name="creator_id",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
