# Generated by Django 4.2.2 on 2023-10-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0074_alter_approvalentry_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalentry",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "Open"),
                    (1, "Pending Approval"),
                    (2, "Approved"),
                    (3, "Cancelled"),
                ],
                default=1,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseheader",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "Open"),
                    (1, "Pending Approval"),
                    (2, "Approved"),
                    (3, "Cancelled"),
                ],
                default=0,
                max_length=30,
            ),
        ),
    ]
