# Generated by Django 4.2.2 on 2023-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0075_alter_approvalentry_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseheader",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "Open"),
                    (1, "Pending Approval"),
                    (2, "Approved"),
                    (3, "Cancelled"),
                ],
                default="Open",
                max_length=30,
            ),
        ),
    ]
