# Generated by Django 4.2.7 on 2023-12-03 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0077_alter_purchaseheader_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SalesLines",
            new_name="SalesLine",
        ),
    ]
